sudo: false
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_638e27b20036_key -iv $encrypted_638e27b20036_iv
  -in python-pokedex-6adc34cac415.json.enc -out python-pokedex-6adc34cac415.json -d
- mkdir -p src/lib
install:
#- pip install -r requirements.txt -t src/lib/
- pip install -r requirements_dev.txt
script:
- pylint src/app
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: python-pokedex
  config: src/app.yaml
  default: true
  on:
    branch: master
